### ISSUE TITLE
Inconsistency with hooks

### ISSUE THREAD

**Issue by chikamichi** [barc/backbone.giraffe#31]
Hi,

Many times, I make the mistake of overriding `beforeDispose`, just as I would override `beforeRender`. Whereas the `beforeRender` hook is part of the public API (the docs say "This is an empty function for you to implement"), `beforeDispose` is not.

I think this is misleading, and internal hooks should be prefixed with `_` to denote the fact that they are not to be overridden. At the same time, one could keep public hooks (`beforeDispose` / `afterDispose`) so as to provide a way to perform synchronous wrapping operations during disposing (although `Giraffe.dispose` triggers "disposing" and "disposed" events, one cannot always rely on them as they are asynchronous by nature).

Actually, this idea is already partially implemented for `initialize`, with `wrapFn` being used to call any existing public hooks (`beforeInitialize`, `afterInitialize`) while an internal after hook is implemented as `_afterInitialize`.

By the way, [hooks are great](http://kaibun.net/blog/2011/08/25/hooks-as-a-service/), so thanks for providing them to begin with :)

**Comment by ryanatkn** [comment]
> Therefore I can't rely on a callback to, say, the "disposing" event to perform operations that must be completed before the rest of the code in Giraffe.dispose runs.

Maybe I'm misinterpreting what you're saying, but in the code above anything triggered in `"disposing"` is guaranteed to run before `beforeDispose`, and anything in `beforeDispose` is guaranteed to run before `_dispose`. (because Backbone.Events callbacks are triggered synchronously and js is single threaded) If you were to add a `"disposing"` handler with `while(true){}`, execution would be blocked infinitely before getting to `beforeDispose`.

If you mean that asynchronous actions may be performed in the `"disposing"` handler or `beforeDispose` hook, it's true that those won't be waited for, but since `beforeDispose` doesn't return a promise that's waited for by `_dispose`, it has the same execution characteristics as an event handler. So really the `beforeDispose` hook is just a convenience in this case, although one difference is that it's more straightforward to override it with a class hierarchy.

**Comment by chikamichi** [comment]
Sorry for the delay in responding here. That makes sense, I overlooked some simple facts about JS environments here :) I am closing this for the main "issue" (inconsistency) you fixed already. Thank you!
